version: "3.7"
services:
  rest-domain-redirect:
    container_name: rest-domain-redirect
    build:
      context: .
      network: host
    environment:
      destinationUrl: "http://domain.com"
    ports:
      - 8080:80
    networks:
      - rest-domain-redirect-network
networks:
  rest-domain-redirect-network:
    driver: bridge